// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserSenderClient is the client API for UserSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSenderClient interface {
	Send(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type userSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSenderClient(cc grpc.ClientConnInterface) UserSenderClient {
	return &userSenderClient{cc}
}

func (c *userSenderClient) Send(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/user.UserSender/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSenderServer is the server API for UserSender service.
// All implementations must embed UnimplementedUserSenderServer
// for forward compatibility
type UserSenderServer interface {
	Send(context.Context, *UserRequest) (*MessageResponse, error)
	mustEmbedUnimplementedUserSenderServer()
}

// UnimplementedUserSenderServer must be embedded to have forward compatible implementations.
type UnimplementedUserSenderServer struct {
}

func (UnimplementedUserSenderServer) Send(context.Context, *UserRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedUserSenderServer) mustEmbedUnimplementedUserSenderServer() {}

// UnsafeUserSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSenderServer will
// result in compilation errors.
type UnsafeUserSenderServer interface {
	mustEmbedUnimplementedUserSenderServer()
}

func RegisterUserSenderServer(s grpc.ServiceRegistrar, srv UserSenderServer) {
	s.RegisterService(&UserSender_ServiceDesc, srv)
}

func _UserSender_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSenderServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserSender/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSenderServer).Send(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSender_ServiceDesc is the grpc.ServiceDesc for UserSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserSender",
	HandlerType: (*UserSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _UserSender_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/user/user.proto",
}
